### ISSUE TITLE
Issue possibly related to Ubuntu 20.04?

### ISSUE THREAD

**Issue by AceOfSpadez54** [coadmunkee/gnome-shell-extension-espresso#15]
The following error is displayed when I attempt to open the settings menu. 
Now I read that this extension is not compatible with Ubuntu 20.04. so I am simply wondering if this is related to that. And if so, can you explain what the issues are?

The settings of extension espresso@coadmunkee.github.com had an error:
```
TypeError: showEspressoBox.prepend is not a function
```

Stack trace:
```
EspressoWidget@/home/joseph/.local/share/gnome-shell/extensions/espresso@coadmunkee.github.com/prefs.js:55:25
buildPrefsWidget@/home/joseph/.local/share/gnome-shell/extensions/espresso@coadmunkee.github.com/prefs.js:313:20
_init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:207:40
OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:132:13
run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:175:20
main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
run@resource:///org/gnome/gjs/modules/script/package.js:222:19
start@resource:///org/gnome/gjs/modules/script/package.js:206:5
@/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```

**Comment by coadmunkee** [comment]
AceOfSpadez54 - the error you are seeing is definitely the version incompatibility between Espresso and Ubuntu 20.04

As you know, Espresso is an Gnome shell extension. You probably saw the statement that Espresso on support Gnome 40. Ubuntu 20.04 uses version Gnome 3.36. There were several changes made for Gnome 40 that are not backwards compatible with earlier versions of Gnome. In particular the version of the GTK libraries that enable the settings dialogue has changed from GTK3 (used with earlier version of Gnome) to GTK4 used with Gnome 40. The error you see above is due to the Espresso extension making function calls that are supported by GTK4 but not by GTK3.

If/when you get to upgrading to Ubuntu 21.10, which uses Gnome 40, the Espresso extension will then work with Ubuntu.

In the meantime, you are probably best off using an extension named Caffeine. Caffeine is the original extension, and Espresso is a fork of that extension (obviously with some changes to make it compatible with Gnome 40). You can find Caffeine on the e.g.o site here: https://extensions.gnome.org/extension/517/caffeine/  or from their github page here: https://github.com/eonpatapon/gnome-shell-extension-caffeine

You shouldn't have any reservations about using Caffeine since Espresso is entirely based on Caffeine.

**Comment by AceOfSpadez54** [comment]
Ahh I see. Thank you for that information.
