### ISSUE TITLE
espresso tray icon wider than normal

### ISSUE THREAD

**Issue by nrbeaton** [coadmunkee/gnome-shell-extension-espresso#16]
A bit nitpicky, but for some reason the espresso tray icon (on Gnome 40.4.0) is wider than other tray icons. See attached screenshots.

![Screenshot from 2021-09-10 13-30-26](https://user-images.githubusercontent.com/6888910/132795172-17cb9355-53f5-42eb-a6e3-70791959ef41.png)
![Screenshot from 2021-09-10 13-30-57](https://user-images.githubusercontent.com/6888910/132795176-ad95e7b2-dc98-4cc0-9cab-ae5e7941d3cc.png)

**Comment by coadmunkee** [comment]
I can see from your screenshots that the Espresso indicator appears to be wider than the next tray icon. Not sure how much time I will be able to dedicate to looking into this one, but will see if I can sort out where it's picking up that width vs the panel indicators. The indicator icons for both the empty cup and the full cup are each 16x16 pixel images, so it isn't due to the icons themselves. I'll have to look into where the togglebutton is inheriting it's style from.

**Comment by nrbeaton** [comment]
Weird. It's a bit irritating but I guess I can live with it. Thanks for looking into it.
